// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://bgsfijdktrghudhgiceh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnc2ZpamRrdHJnaHVkaGdpY2VoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0ODk2NDcsImV4cCI6MjA3NjA2NTY0N30.87tYvw4gE-XL7oi8iQmqk90hE6lyZ2aVp5TK9oCUr6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);